std = "roblox"
exclude = ["references/**", "**/_Index/**", "benchmarks/**", "scratch/**", "comparison/**"]

[rules]
unused_variable = "warn"
multiple_assign = "allow"
empty_if = "warn"
empty_loop = "warn"
shadowing = "allow"