[package]
name = "protheeuz/satset"
description = "High-performance, buffer-backed hybrid networking for Roblox with zero-allocation delta synchronization."
version = "0.4.1"
authors = ["Iqbal F <iqbalfauzien@pm.me", "LVSandals <lvsandals-rbx@pm.me>"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"benchmarks",
	"CHANGELOG.md",
	"comparison",
	"CONTRIBUTING.md",
	"DevPackages",
	"package.json",
	"Packages",
	"docs",
	"README.md",
	"references",
	"rokit.toml",
	"scratch",
	"selene.toml",
	"stylua.toml",
	"tests",
]

[dev-dependencies]
ByteNet = "ffrostflame/bytenet@0.4.6"
BridgeNet2 = "ffrostflame/bridgenet2@1.0.0"
Warp = "imezx/warp@1.0.0"
